


server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka


spring:
  cloud:
    gateway:
        routes:
          - id : auth
            uri : lb://AUTH
            predicates:
              - Path=/api/auth/**

          - id: chatbot-http
            uri: lb://CHATBOT
            predicates:
              - Path=/api/chatbot/**

          - id: chatbot-websocket
            uri: lb://CHATBOT
            predicates:
              - Path=/api/ws/**
#            filters:
#              - RewritePath=/api/ws/(?<segment>.*), /$\{segment}

  application:
    name: gateway