


server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka


spring:
  cloud:
    gateway:
        routes:
          - id : auth
            uri : lb://AUTH
            predicates:
              - Path=/api/auth/**
          - id : chatbot
            uri : lb//CHATBOT
            predicates:
              - Path=/api/chatbot/**

  application:
    name: gateway