
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka/

spring:
  application:
    name: chatbot

  data:
    mongodb:
      uri: ENC(P5G3E6YLr2b2l83lNHJRcNll3EJVVHeO21nsjn4SNPBm6oM/L5nPixP4ORvpnzWOLC44oi3KfieZ2LF2t/UaN1KvBpCZVZ4yvCM3yG4YwIlD3x81fDw3uQ==)

    redis:
      host: ENC(r5G5fBs7eUDEyyWTGM7SUtFqqRgp/rtL)
      port: 6379

  rabbitmq:
    host: ENC(r5G5fBs7eUDEyyWTGM7SUtFqqRgp/rtL)
    port: 4885
    virtual-host: /
    username: ENC(6KNNGCEX5RW/lyZgNM/kWw==)
    password: ENC(1XVadta2Ywz2Ba+4k+Y06s2PGebCMlmX)

  profiles:
    include: secret

  datasource:
    url: ${database.dev.url}
    username: ${database.dev.username}
    password: ${database.dev.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT Secret Key
app:
  secret-key: 12341324154321646543432474vccc38xg4bfjagbf3g2r123wdascgry5465fegfjteyrrg